{
  "formatVersion": "1.1",
  "component": {
    "group": "com.futureworkshops.mobileworkflow.plugin",
    "module": "charts",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "aces3kf2qzhdrkeqsymx7kwwpm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "charts-0.0.2.aar",
          "url": "charts-0.0.2.aar",
          "size": 56710,
          "sha512": "dc689a0c876a4d5bb1b8f8d887d9db8483c9385145c2af08599672cfe55307359b50b478e85ecd89ab1cd821f80c831fb6409c876fd5e7755339c42098e25fd4",
          "sha256": "6a524ee591be7848a131fd37d2200bc6b6ee9f1dbdfb960a2e137e1d16fe7375",
          "sha1": "663ae4ce8e9c42dc270c82fc2ab01b9d616464f3",
          "md5": "920ec0a785e3421bf2636228426ca614"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.futureworkshops.mobileworkflow",
          "module": "mw-core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.github.PhilJay",
          "module": "MPAndroidChart",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.github.matthewyork",
          "module": "ColoursLibrary",
          "version": {
            "requires": "1.0.+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ColoursLibrary",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "charts-0.0.2.aar",
          "url": "charts-0.0.2.aar",
          "size": 56710,
          "sha512": "dc689a0c876a4d5bb1b8f8d887d9db8483c9385145c2af08599672cfe55307359b50b478e85ecd89ab1cd821f80c831fb6409c876fd5e7755339c42098e25fd4",
          "sha256": "6a524ee591be7848a131fd37d2200bc6b6ee9f1dbdfb960a2e137e1d16fe7375",
          "sha1": "663ae4ce8e9c42dc270c82fc2ab01b9d616464f3",
          "md5": "920ec0a785e3421bf2636228426ca614"
        }
      ]
    }
  ]
}
